name: Block
'on':
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - packages/account/**
      - packages/common/**
      - packages/tx/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - packages/account/**
      - packages/common/**
      - packages/tx/**
jobs:
  test-block:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v1
      - run: npm install
        working-directory: '${{ env.cwd }}'
      - run: npx lerna run lint --scope ethereumjs-block
      - run: npm run test:node
        working-directory: '${{ env.cwd }}'
      - run: npm run test:browser
        working-directory: '${{ env.cwd }}'
      - uses: codecov/codecov-action@v1
        with:
          file: '${{ env.cwd }}/coverage/lcov.info'
    env:
      cwd: '${{github.workspace}}/packages/block'
