name: Common
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Common-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'

      - name: Use npm v7 for workspaces support 
        run: npm i -g npm@7

      # Installs root dependencies,
      # ignoring postinstall script to build all packages.
      - run: npm install --ignore-scripts
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}

      # Builds current package and the ones it depends from.
      - run: npm run build --workspace=@ethereumjs/common
        working-directory: ${{github.workspace}}

      - name: Build deps used in tests (for karma)
        run: npm run build --workspace=ethereumjs-util
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: common
        if: ${{ matrix.node-version == 12 }}

      - run: npm run lint
