name: Util
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/util

defaults:
  run:
    working-directory: packages/util

jobs:
  test-util:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Util-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          path: '**/node_modules'

      - name: Update to npm v7 for workspaces support 
        run: npm i -g npm@7

      # Installs dependencies and builds all packages (if cache hit failed)
      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}

      # Builds fresh packages (if cache hit succeeded)
      - run: npm run build --workspaces
        if: steps.cache.outputs.cache-hit == 'true'
        working-directory: ${{github.workspace}}

      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: util
        if: ${{ matrix.node-version == 12 }}

      - run: npm run lint
