name: vm-coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run coverage
      - run: npm run coveralls

      - name: Post coverage data to coveralls.io for analysis
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .nyc_output/lcov.info
