name: VM Nightly
'on':
  schedule:
    - cron: 0 0 * * *
jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: npm run test:API
        working-directory: '${{ env.cwd }}'
      - run: npm run test:API:browser
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-vm-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: npm run test:state:allForks
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
        working-directory: '${{ env.cwd }}'
      - run: npm run test:blockchain
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
  test-vm-slow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npx lerna bootstrap --scope ethereumjs-vm --ignore-scripts --include-dependencies --no-ci
      - run: npx lerna run --scope ethereumjs-vm --include-dependencies build
      - run: npm run test:state:slow
        working-directory: '${{ env.cwd }}'
    env:
      cwd: '${{github.workspace}}/packages/vm'
